import type { ReviewField, ReviewStatus as Status } from '../types/ocrLayout.types';
import { ConfidenceBadge } from './ConfidenceBadge';
import { ReviewStatus } from './ReviewStatus';
import { reviewFieldLabel } from '../utils/groupReviewFields';

export function EvidencePanel({ field, onUpdate, onDecide }: { field: ReviewField | null; onUpdate: (patch: { value?: string; status?: Status }) => void; onDecide: (status: Exclude<Status, 'pending_review'>) => void }) {
  if (!field) return <section className="docdai-evidence-panel"><span className="docdai-eyebrow">Evidencia visual</span><p className="mb-0 text-secondary">Selecciona un dato para consultar su origen en el documento.</p></section>;
  const isEdited = field.value !== field.originalValue;
  return <section className="docdai-evidence-panel"><div className="d-flex justify-content-between gap-2 align-items-start"><div><span className="docdai-eyebrow">Evidencia visual · {reviewFieldLabel(field.evidence.field)}</span><h2>{field.value || 'No especificado en la receta'}</h2></div><ReviewStatus status={field.status} /></div><label className="form-label small fw-semibold mt-2">Valor propuesto</label><input className="form-control" value={field.value} onChange={(event) => onUpdate({ value: event.target.value, status: event.target.value === field.originalValue ? field.status : 'corrected' })} /><p className="small text-secondary mb-2">También puedes seleccionar un bloque sobre el documento para asignar su texto a este dato.</p><div className="docdai-evidence-source"><small>Texto detectado en el documento</small><p>“{field.evidence.source_text}”</p></div>{isEdited ? <div className="docdai-original-value"><small>Valor original conservado</small><strong>{field.originalValue}</strong></div> : null}<div className="d-flex flex-wrap gap-2 align-items-center small text-secondary"><span>Página {field.evidence.page ?? 'no disponible'}</span><ConfidenceBadge confidence={field.evidence.confidence} /></div><div className="d-flex gap-2 flex-wrap mt-3"><button type="button" className="btn btn-sm btn-success" onClick={() => onDecide('approved')}>Aprobar dato</button><button type="button" className="btn btn-sm btn-outline-primary" onClick={() => onDecide('corrected')}>Marcar corregido</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => onDecide('rejected')}>Rechazar</button></div></section>;
}
