import type { ReviewField, ReviewStatus as Status } from '../types/ocrLayout.types';
import { ConfidenceBadge } from './ConfidenceBadge';
import { ReviewStatus } from './ReviewStatus';

export function EvidencePanel({ field, onUpdate }: { field: ReviewField | null; onUpdate: (patch: { value?: string; status?: Status }) => void }) {
  if (!field) return <section className="docdai-evidence-panel"><span className="docdai-eyebrow">Evidencia</span><p className="mb-0 text-secondary">Selecciona un campo para consultar su origen.</p></section>;
  const isEdited = field.value !== field.originalValue;
  return <section className="docdai-evidence-panel"><div className="d-flex justify-content-between gap-2 align-items-start"><div><span className="docdai-eyebrow">Evidencia · {field.evidence.field}</span><h2>{field.value || 'No detectado'}</h2></div><ReviewStatus status={field.status} /></div><label className="form-label small fw-semibold mt-2">Valor propuesto</label><input className="form-control" value={field.value} onChange={(event) => onUpdate({ value: event.target.value, status: event.target.value === field.originalValue ? field.status : 'corrected' })} /><div className="docdai-evidence-source"><small>Texto OCR original</small><p>“{field.evidence.source_text}”</p></div>{isEdited ? <div className="docdai-original-value"><small>Valor OCR conservado</small><strong>{field.originalValue}</strong></div> : null}<div className="d-flex flex-wrap gap-2 align-items-center small text-secondary"><span>Página {field.evidence.page ?? 'no disponible'}</span><ConfidenceBadge confidence={field.evidence.confidence} /><span>Regla: {field.evidence.match_type}</span></div><div className="d-flex gap-2 flex-wrap mt-3"><button type="button" className="btn btn-sm btn-success" onClick={() => onUpdate({ status: 'approved' })}>Aprobar campo</button><button type="button" className="btn btn-sm btn-outline-primary" onClick={() => onUpdate({ status: 'corrected' })}>Marcar corregido</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => onUpdate({ status: 'rejected' })}>Rechazar</button></div></section>;
}
