from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.domain.entities.clinical_patient import ClinicalPatient


class PatientRepository(Protocol):
    def save(self, *, patient: ClinicalPatient) -> None: ...
    def get(self, *, patient_id: UUID) -> ClinicalPatient | None: ...
    def list(self) -> list[ClinicalPatient]: ...
    def find_by_curp(self, *, curp: str) -> list[ClinicalPatient]: ...
    def find_by_nss(self, *, nss: str) -> list[ClinicalPatient]: ...
    def find_by_name_and_date_of_birth(self, *, name: str, date_of_birth: object) -> list[ClinicalPatient]: ...
    def find_by_normalized_name(self, *, name: str) -> list[ClinicalPatient]: ...
